import {StyleSheet} from 'react-native';
import Colors from '../../common/Colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.loginBack,
        justifyContent: 'center',
        // alignItems: 'center',
    },
    loginForm: {
        height: 512,
        width: 480,
        backgroundColor: '#fff',
        borderRadius: 16,
        flexDirection: 'column',
        alignItems: 'flex-start',
        padding: (40, 40, 28, 40),
        display: 'flex',
        left: 0,
        top: 0,
        alignSelf: 'stretch',
        marginTop: 28,
        justifyContent: 'center', 
    },
    header: {
        fontFamily: 'Inter',
        fontStyle: 'normal',
        fontWeight: '700',
        alignItems: 'center',
        color: '#1F4EC7',
        position: 'static',
        width: 400,
        height: 34,
        left: 40,
        top: 40,
        margin: (40, 0),
    },
    loginInput: {
        backgroundColor: '#F5F5F5',
        position: 'static',
        width: 400,
        height: 48,
        alignItems: 'center',
        flexDirection: 'row',
        borderRadius: 12,
        marginTop: 32,
        marginVertical: 10,
        paddinVertical: 12,
        color: 'black',
        alignItems: 'center',
        fontFamily: 'Inter',
        fontStyle: 'normal',
        fontSize: 16, 
        lineHeight: 16, 
        order: 0,
        margin: (0, 10),
    },
    btn: {
        width: 400,
        height: 48,
        marginVertical: 10,
        flexDirection: 'row',
        left: 10,
    }
})